### ISSUE TITLE
Node panicing when RPC timeout

### ISSUE THREAD

**Issue by dimiandre** [sentinel-official/dvpn-node#7]
**Describe the bug**
When connection with the tendermint rpc timeout the node is panicking

`I[2020-12-21|03:44:50.419] Updated node status                          tx_hash=1276CA033D8BCB33B8BFF13E99368B14109E8A51278D83518A97B038CF3F4ABA
panic: ABCIQuery: Post "https://rpc.turing.sentinel.co:443": dial tcp: lookup rpc.turing.sentinel.co on 213.186.33.99:53: read udp 172.17.0.4:42557->213.186.33.99:53: i/o timeout

goroutine 209 [running]:
github.com/sentinel-official/dvpn-node/node.(*Node).Start.func1(0xc0011be048)
        /go/src/github.com/sentinel-official/dvpn-node/node/node.go:39 +0x58
created by github.com/sentinel-official/dvpn-node/node.(*Node).Start
        /go/src/github.com/sentinel-official/dvpn-node/node/node.go:37 +0x54
`

**Expected behavior**
Maybe retry or restart?

**OS:**
Ubuntu 20.04
dVPN Node running under docker

**Comment by bsrinivas8687** [comment]
@dimiandre It looks like the issue is with DNS resolution. Can you please check your DNS servers configuration.
