### ISSUE TITLE
Node keeps Crashing  (data.db corrupted)

### ISSUE THREAD

**Issue by HammontreeArt** [sentinel-official/dvpn-node#98]
**Describe the bug**
The data.db file keeps getting corrupted and node crashes.

**To Reproduce**
1. Connect to a new node v0.3.0
2. Disconnect from the node
3. wait until the node attempts to remove "Stale" connection
4. Node crashes with the error

** Steps to Restart Node **
1. Shut down node
5. rename or remove the /roor/.sentinelnode/data.db
6. Restart the node

**Expected behavior**
The node should not drop

**ERROR**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x140c7bc]
goroutine 450 [running]:
github.com/sentinel-official/dvpn-node/node.(*Node).jobUpdateSessions(0xc000e4c930)
        /go/src/github.com/sentinel-official/dvpn-node/node/jobs.go:109 +0x37c
github.com/sentinel-official/dvpn-node/node.(*Node).Start.func3()
        /go/src/github.com/sentinel-official/dvpn-node/node/node.go:52 +0x1d
created by github.com/sentinel-official/dvpn-node/node.(*Node).Start
        /go/src/github.com/sentinel-official/dvpn-node/node/node.go:51 +0x110

**Desktop (please complete the following information):**
 - Ubuntu 
 - 20.04 LTS

**Additional context**
Using Exidio APP on an Android Device to connect to Node for testing.

**Comment by HammontreeArt** [comment]
Additional Note:

Every node that I connect to ends up with the data.db file corrupted. I have a couple nodes that I have not connected to yet and they are still running without any downtime.

Q: Do you think there is something in the Exidio APP that could be corrupting the data.db file?

**Comment by HammontreeArt** [comment]
Attached is a copy of the corrupted data.db file.    
I changed the extension from .db to .txt so I could attach it here. 


[data-saved01.txt](https://github.com/sentinel-official/dvpn-node/files/8455190/data-saved01.txt)

**Comment by HammontreeArt** [comment]
I updated DVPN-Node to latest version v0.3.1. and I'm monitoring for the error.
